spring:
  datasource:
    url: ${SRM_DB_URL}
    username: ${SRM_DB_USERNAME}
    password: ${SRM_DB_PASSWORD}
  flyway:
    enabled: true
  sql:
    init:
      mode: never

management:
  endpoint:
    health:
      probes:
        enabled: true

srm:
  jwt-secret: ${SRM_JWT_SECRET}
